# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Icmperf < Formula
  desc ""
  homepage ""
  version "1.0.2"

  on_macos do
    on_intel do
      url "https://github.com/b4nst/icmperf/releases/download/v1.0.2/icmperf_Darwin_x86_64.tar.gz"
      sha256 "ed2add253698f6e74d65dbe33b26def563a14aba0b81da6645728edb563b108d"

      def install
        bin.install "icmperf"
      end
    end
    on_arm do
      url "https://github.com/b4nst/icmperf/releases/download/v1.0.2/icmperf_Darwin_arm64.tar.gz"
      sha256 "caa0f2c736791c978f2026492224d8871ccdb8a937a689d3510ac6c8e49bdc3e"

      def install
        bin.install "icmperf"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/b4nst/icmperf/releases/download/v1.0.2/icmperf_Linux_x86_64.tar.gz"
        sha256 "33c0aa6c528349fe2a58d47aa7b7b4b98abe4ede3c983b57b1c1885a75b8338a"

        def install
          bin.install "icmperf"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/b4nst/icmperf/releases/download/v1.0.2/icmperf_Linux_arm64.tar.gz"
        sha256 "51c10f2e827d2169d39260d71ee8ad0c05d48514d602ebb11fb8732a8cd0ab07"

        def install
          bin.install "icmperf"
        end
      end
    end
  end
end
