# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Icmperf < Formula
  desc ""
  homepage ""
  version "1.2.1"

  on_macos do
    on_intel do
      url "https://github.com/b4nst/icmperf/releases/download/v1.2.1/icmperf_Darwin_x86_64.tar.gz"
      sha256 "91674bdd7522b61dbb4108b8b3b69508a69b1a688ff3d8c6a87a07f13e68a87e"

      def install
        bin.install "icmperf"
      end
    end
    on_arm do
      url "https://github.com/b4nst/icmperf/releases/download/v1.2.1/icmperf_Darwin_arm64.tar.gz"
      sha256 "4f88aa73ea6b1de9607ee3f7b3569b3d5a6a2cad67a5e48c47e31d8353fc2acc"

      def install
        bin.install "icmperf"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/b4nst/icmperf/releases/download/v1.2.1/icmperf_Linux_x86_64.tar.gz"
        sha256 "97a861d26c454fadf0ffa0b4a1837b413373d1f72de51ca500c450fdf5758e4d"

        def install
          bin.install "icmperf"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/b4nst/icmperf/releases/download/v1.2.1/icmperf_Linux_arm64.tar.gz"
        sha256 "05d632db5539f6aaaed7974f899183870e9470d47b5b486ae14e5e80ea4d5564"

        def install
          bin.install "icmperf"
        end
      end
    end
  end
end
