# This file was generated by GoReleaser. DO NOT EDIT.
class Rename < Formula
  desc "Cli tool built to help you deal with your day-to-day git work"
  homepage "https://github.com/b4nst/rename"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/b4nst/rename/releases/download/v0.2.0/rename_0.2.0_macOS_amd64.tar.gz"
    sha256 "7cda81fba019b10ce13283831eb86f076030ed689183517bee93c4f92d1e12fa"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/b4nst/rename/releases/download/v0.2.0/rename_0.2.0_linux_amd64.tar.gz"
      sha256 "c396aaac8364e11347184ef5322aa10d5c4020f5d3093c8efc4d01fc3642dde3"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/b4nst/rename/releases/download/v0.2.0/rename_0.2.0_linux_arm64.tar.gz"
        sha256 "28b078122e800bda190960b83c35bda5c5d4f9da32cc340dd2121e463dac31df"
      else
      end
    end
  end
  
  head do
    url "https://github.com/b4nst/rename.git"
    depends_on "go"
  end

  def install
    bin.install "bin/rename"
  end

  test do
    help_text = shell_output("#{bin}/rename -h")
    assert_includes help_text, "Usage:"
  end
end
