# This file was generated by GoReleaser. DO NOT EDIT.
class Turbogit < Formula
  desc "Cli tool built to help you deal with your day-to-day git work"
  homepage "https://github.com/b4nst/turbogit"
  version "1.0.0"

  head do
    url "https://github.com/b4nst/turbogit.git"
    depends_on "go"
  end

  bottle :unneeded

  if OS.mac?
    url "https://github.com/b4nst/turbogit/releases/download/v1.0.0/turbogit_1.0.0_macOS_amd64.tar.gz"
    sha256 "06254581f1c21d34cf2a662ac2231d3369e98faf678553f220f2494e6d03dfc7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/b4nst/turbogit/releases/download/v1.0.0/turbogit_1.0.0_linux_amd64.tar.gz"
      sha256 "78fd0512142f174e2595a152ea70ceaf1dc62232713d878267a93b81d3d4fc4c"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/b4nst/turbogit/releases/download/v1.0.0/turbogit_1.0.0_linux_arm64.tar.gz"
        sha256 "828f1c2806e1ed624d76091ba050eb8455a9fcb210282daa065d2bfc9e7fd307"
      end
    end
  end

  def install
    bin.install "bin/tug"
    etc.install "config/tug.toml"
    (bash_completion/"tug.sh").write `#{bin}/tug completion bash`
    (zsh_completion/"_tug").write `#{bin}/tug completion zsh`
    (fish_completion/"tug.fish").write `#{bin}/tug completion fish`
  end

  test do
    help_text = shell_output("#{bin}/tug --help")
    assert_includes help_text, "Usage:"
  end
end
